import { Providers } from "@/components/providers";
import { QueryProvider } from "@/components/query-provider";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "../lib/orpc.server";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.className} antialiased`}>
        <QueryProvider>
          <Providers themeProps={{ attribute: "class", defaultTheme: "light" }}>{children}</Providers>
        </QueryProvider>
      </body>
    </html>
  );
}
